config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'

  resources :decks, only: [ :show ] do
    resources :flashcards, only: [ :show ] do
      resources :attempts, only: [ :create, :destroy ]
    end
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get 'topics', to: 'topics#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attempt.rb
class Attempt < ApplicationRecord
  belongs_to :user
  belongs_to :flashcard
end

app/models/deck.rb
class Deck < ApplicationRecord
  belongs_to :topic
  has_many :flashcards
  has_one :attempt, through: :flashcards
end

app/models/flashcard.rb
class Flashcard < ApplicationRecord
  belongs_to :question_type
  belongs_to :deck
  has_one :attempt
end

app/models/question_type.rb
class QuestionType < ApplicationRecord
  has_many :flashcards
end

app/models/topic.rb
class Topic < ApplicationRecord
  has_many :decks
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :attempts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name])
  end
end
# app/controllers/application_controller.rb

def default_url_options
  { host: ENV["DOMAIN"] || "localhost:3000" }
end

app/controllers/attempts_controller.rb
class AttemptsController < ApplicationController
  def create
    @deck = Deck.find(params['deck_id'])
    @flashcard = Flashcard.find(params['flashcard_id'])
    if @flashcard.question_type.name == 'multiple-choice'
      @submission = params['flashcard']['answer']
    elsif @flashcard.question_type.name == 'sort'
      @submission = params["current_order"]
    end

    @correct_answer = @flashcard.answer

    if @flashcard.attempt
      # update the attempt
      @attempt = @flashcard.attempt
      if @submission == @correct_answer
        @attempt.attempt_correct = true
      else
        @attempt.attempt_correct = false
      end
    else
      # create the attempt
      @attempt = Attempt.new(user: current_user, flashcard: @flashcard, attempted: DateTime.now, attempt_correct: false, submission: nil)
      @attempt.attempt_correct = true if @submission == @correct_answer
    end

    @attempt.submission = @submission
    @attempt.save

    redirect_to deck_flashcard_path(@deck, @flashcard, display: 'result')
  end
end

app/controllers/decks_controller.rb
class DecksController < ApplicationController
  def show
    @deck = Deck.find(params[:id])
    @score = mark(@deck)
    @review = incorrect(@deck)
  end

  private

  def mark(deck)
    correct = []
    incorrect = []
    deck.flashcards.each do |card|
      card.attempt.attempt_correct ? correct << card : incorrect << card
    end
    return "#{correct.count} / #{incorrect.count + correct.count}"
  end

  def incorrect(deck)
    wrong = []
    deck.flashcards.each do |card|
      wrong << card if !card.attempt.attempt_correct
    end
    return wrong
  end
end

app/controllers/flashcards_controller.rb
class FlashcardsController < ApplicationController
  def show
    @deck = Deck.find(params[:deck_id])
    @flashcard = Flashcard.find(params[:id])
    @type = @flashcard.question_type
    @deck_card_count = @deck.flashcards.count
    @question_number = @deck.flashcards.find_index(@flashcard) + 1

    # clear attempts
    if @flashcard == @deck.flashcards.first && params[:display] != 'result'
      @deck.flashcards.each do |flashcard|
        flashcard.attempt.destroy if flashcard.attempt
      end
    end

    # set up question
    if @type.name == 'multiple-choice'
      @options = [@flashcard.answer, @flashcard.choice1, @flashcard.choice2, @flashcard.choice3].sample(4)
    elsif @type.name == 'sort'
      @options = [@flashcard.sort1, @flashcard.sort2, @flashcard.sort3, @flashcard.sort4]
    end

    if params[:display] == 'result'
      @submission = @flashcard.attempt.submission

      if @type.name == 'sort'
        @submission_array = @submission.split('~')
        @answer_array = @flashcard.answer.split('~')
      end

      # how many wrong answers so far?
      @wrong_attempts = 0
      @deck.flashcards.each do |flashcard|
        if flashcard.attempt && !flashcard.attempt.attempt_correct
          @wrong_attempts += 1
        end
      end

      if @wrong_attempts < 2
        @next_question_index = @deck.flashcards.find_index(@flashcard) + 1
      end
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home ]

  def home
    @topic = Topic.where(name: 'Ruby')
    @deck = Deck.where(name: 'Hash & Symbols')
    @flashcards = @deck[0].flashcards
    @correct_attempts = 0
    @flashcards.each do |flashcard|
      @correct_attempts += 1 if flashcard.attempt && flashcard.attempt.attempt_correct
    end
    @completed = (@correct_attempts >= 3)
  end
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  def index
    @topics = Topic.all
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/meta_tags_helper.rb
# app/helpers/meta_tags_helper.rb

module MetaTagsHelper
  def meta_title
    content_for?(:meta_title) ? content_for(:meta_title) : DEFAULT_META["meta_title"]
  end

  def meta_description
    content_for?(:meta_description) ? content_for(:meta_description) : DEFAULT_META["meta_description"]
  end

  def meta_image
    meta_image = (content_for?(:meta_image) ? content_for(:meta_image) : DEFAULT_META["meta_image"])
    # little twist to make it work equally with an asset or a url
    meta_image.starts_with?("http") ? meta_image : image_url(meta_image)
  end
end

app/views/decks/show.html.erb
<div class="scene-lg">


  <div class="show-info">
    <h4 class = "main-title"> <%= @score %> Cards Correct</h4>
    <br>
    <%= link_to "Repeat Deck", deck_flashcard_path(@deck, @deck.flashcards.first), class: "btn pill-end1" %>
    <%= link_to "New Deck", topics_path, class: "btn pill-end2" %>
    <%# <button class = "btn pill">Repeat Deck</button>
    <button class = "btn pill">Choose Deck</button> %>
    <br>
    <br>
  </div>
  <div class = 'review'>
    <% if @review.count > 0 %>
      <h4>Areas to Review</h4>
      <table>
        <% @review.each do |card| %>
          <tr>
            <td> <%= card.question %> </td>
          </tr>
        <% end %>
      </table>
    <% end %>
  </div>


    <i class = "star first_still"><%= image_tag 'sparkle.png', style: "width: 20px;"%></i>
    <i class = "star second_still"><%= image_tag 'sparkle.png', style: "width: 20px;"%></i>
    <i class = "star third_still"><%= image_tag 'sparkle.png', style: "width: 20px;"%></i>
    <i class = "star fourth_still"><%= image_tag 'sparkle.png', style: "width: 20px;"%></i>
    <i class = "star fifth_still"><%= image_tag 'sparkle.png', style: "width: 20px;"%></i>
    <i class = "star sixth_still"><%= image_tag 'sparkle.png', style: "width: 20px;"%></i>
    <i class = "star seventh_still"><%= image_tag 'sparkle.png', style: "width: 20px;"%></i>
    <%# <i class = "star eigth_still"><%= image_tag 'sparkle.png', style: "width: 20px;"%>
    <%# <i class = "star ninth_still"><%= image_tag 'sparkle.png', style: "width: 20px;"%>
    <i class = "star tenth_still"><%= image_tag 'sparkle.png', style: "width: 20px;"%></i>
    <!-- <img class = "astroid one"src="astroid.png" alt="astroid">
      <img class="astroid two" src="astroid.png" alt="astroid"> -->
    <!-- <style>
      @keyframes move {

        110% {
          transform: translate(0)
        }

        0% {
          transform: translate(300px)
        }
      }
    </style> -->
    <!-- <div id="axis" class="five">
      <img class="astroid object plane move-ne" src="astroid.png" alt="star">
    </div> -->
    <!-- <img class="explosion" src="explosion.png" alt="boom"> -->
    <!-- <div id="axis" class="box">
      <img class="astroid2 object plane move-ne" src="astroid.png" alt="star">
    </div> -->
    <div class="rocket-and-earth">
      <div id="axis" class="six">

        <svg xmlns="http://www.w3.org/2000/svg" version="1" viewbox="0 0 741 1255" width="100" height="120" id="player1"
          class="rocket-lg rocket-landing">
          <path fill="#1560d6"
            d="M565 728c-6 68-15 130-29 186 88 38 156 106 187 188 12-32 18-65 18-100 0-116-70-217-176-274zM265 1020l8 25h194l9-25H265z" />
          <path fill="#e83d37" d="M210 937c8 30 17 58 26 83h269c9-25 18-53 26-83H210z" />
          <path fill="#1560d6"
            d="M0 1002c0 35 6 68 18 100 31-82 99-150 187-188-14-55-23-118-29-186A314 314 0 0 0 0 1002z" />
          <path fill="#DFE3E5"
            d="M571 585c0-125-30-241-67-337a395 395 0 0 1-270 0c-36 94-64 209-64 337a1658 1658 0 0 0 34 329l6 23h321l5-23a1313 1313 0 0 0 35-329z" />
          <circle fill="#B8BDBF" cx="370" cy="481" r="100" />
          <path fill="#ead3b0" d="M455 481a85 85 0 1 1-170 0 85 85 0 0 1 170 0z" />
          <path fill="#1560d6" d="M234 248a394 394 0 0 0 270 0C446 98 370 0 370 0c-9 10-81 104-136 248z" />
        </svg>
      </div>
        <!-- <img class="object coin move-down" src="images/coin.png" /> -->
        <%# <img class = "earth" src="app/assets/images/earth.png" alt="planet"> %>
        <i class = "earth"><%= image_tag 'earth.png'%></i>
    </div>
    </div>

<%# <h2>⭐️Deck Complete⭐️</h2>
<br> %>

app/views/flashcards/show.html.erb
<div id ="top">

  <% if params[:display] == 'result' %>
    <% if @wrong_attempts >= 2 %>
      <div class="scene-lg-move">
      <%= image_tag 'sparkle.png', style: "width: 20px;", class: "star first"%>
      <%= image_tag 'sparkle.png', style: "width: 20px;", class: "star second"%>
      <%= image_tag 'sparkle.png', style: "width: 20px;", class: "star third"%>
      <%= image_tag 'sparkle.png', style: "width: 20px;", class: "star fourth"%>
      <%= image_tag 'sparkle.png', style: "width: 20px;", class: "star fifth"%>
      <%= image_tag 'sparkle.png', style: "width: 20px;", class: "star sixth"%>
      <%= image_tag 'sparkle.png', style: "width: 20px;", class: "star seventh"%>
      <%= image_tag 'sparkle.png', style: "width: 20px;", class: "star eigth"%>
      <%= image_tag 'sparkle.png', style: "width: 20px;", class: "star nineth"%>
      <%= image_tag 'sparkle.png', style: "width: 20px;", class: "star tenth"%>
      <!-- <img class = "astroid one"src="astroid.png" alt="astroid">
        <img class="astroid two" src="astroid.png" alt="astroid"> -->
      <!-- <style>
        @keyframes move {

          110% {
            transform: translate(0)
          }

          0% {
            transform: translate(300px)
          }
        }
      </style> -->
      <div id="axis" class="four">
        <%= image_tag 'astroid.png', class: "astroid-lg"%>
        <%# <img class="astroid-lg object plane move-ne" src="astroid.png" alt="star"> %>
      </div>
      <%= image_tag 'explosion.png', class: "explosion"%>
      <%# <img class="explosion fadeOut" src="explosion.png" alt="boom"> %>
      <%# <img class="astronaut" src="astronaut.png" alt="astronaut"> %>
      <%= image_tag 'astronaut.png', class: "astronaut"%>
      <!-- <div id="axis" class="box">
        <img class="astroid2 object plane move-ne" src="astroid.png" alt="star">
      </div> -->
      <svg xmlns="http://www.w3.org/2000/svg" version="1" viewbox="0 0 741 1255" width="100" height="120" id="player1"
        class="rocket-lg-move">
        <path fill="#1560d6"
          d="M565 728c-6 68-15 130-29 186 88 38 156 106 187 188 12-32 18-65 18-100 0-116-70-217-176-274zM265 1020l8 25h194l9-25H265z" />
        <path fill="#e83d37" d="M210 937c8 30 17 58 26 83h269c9-25 18-53 26-83H210z" />
        <path fill="#1560d6"
          d="M0 1002c0 35 6 68 18 100 31-82 99-150 187-188-14-55-23-118-29-186A314 314 0 0 0 0 1002z" />
        <path fill="#DFE3E5"
          d="M571 585c0-125-30-241-67-337a395 395 0 0 1-270 0c-36 94-64 209-64 337a1658 1658 0 0 0 34 329l6 23h321l5-23a1313 1313 0 0 0 35-329z" />
        <circle fill="#B8BDBF" cx="370" cy="481" r="100" />
        <path fill="#ead3b0" d="M455 481a85 85 0 1 1-170 0 85 85 0 0 1 170 0z" />
        <path fill="#1560d6" d="M234 248a394 394 0 0 0 270 0C446 98 370 0 370 0c-9 10-81 104-136 248z" />
      </svg>
    </div>
  <% end %>
<% end %>
<br>
</div>
<div class = "bottom">
  <div class = "nav-bar">
    <h6 class = "nav-head">Quiz</h6>
    <h5 class = "nav-topic"><%= @flashcard.deck.topic.name %></h5>
  </div>



<%# end of explosion cut scene %>


  <% if params[:display] == 'result' %>
    <% if @flashcard.attempt.attempt_correct %>
      <div class = "scene">
          <%# <img class = "star first" src = "app/assets/images/sparkle.png" alt="star" >
          <img class="star second" src="sparkle.png" alt="star">
          <img class="star third" src="sparkle.png" alt="star">
          <img class="star fourth" src="sparkle.png" alt="star">
          <img class="star fifth" src="sparkle.png" alt="star"> %>

        <%= image_tag 'sparkle.png', style: "width: 20px;", class: "star first"%>
        <%= image_tag 'sparkle.png', style: "width: 20px;", class: "star second"%>
        <%= image_tag 'sparkle.png', style: "width: 20px;", class: "star third"%>
        <%= image_tag 'sparkle.png', style: "width: 20px;", class: "star fourth"%>
        <%= image_tag 'sparkle.png', style: "width: 20px;", class: "star fifth"%>
          <!-- <img class = "astroid one"src="astroid.png" alt="astroid">
          <img class="astroid two" src="astroid.png" alt="astroid"> -->



          <svg xmlns="http://www.w3.org/2000/svg" version="1" viewbox="0 0 741 1255" width="67.7" height="67.7" id="player1"
            class="rocket">
            <path fill="#1560d6"
              d="M565 728c-6 68-15 130-29 186 88 38 156 106 187 188 12-32 18-65 18-100 0-116-70-217-176-274zM265 1020l8 25h194l9-25H265z" />
              <path fill="#e83d37" d="M210 937c8 30 17 58 26 83h269c9-25 18-53 26-83H210z" />
              <path fill="#1560d6" d="M0 1002c0 35 6 68 18 100 31-82 99-150 187-188-14-55-23-118-29-186A314 314 0 0 0 0 1002z" />
              <path fill="#DFE3E5"
                d="M571 585c0-125-30-241-67-337a395 395 0 0 1-270 0c-36 94-64 209-64 337a1658 1658 0 0 0 34 329l6 23h321l5-23a1313 1313 0 0 0 35-329z" />
              <circle fill="#B8BDBF" cx="370" cy="481" r="100" />
              <path fill="#ead3b0" d="M455 481a85 85 0 1 1-170 0 85 85 0 0 1 170 0z" />
              <path fill="#1560d6" d="M234 248a394 394 0 0 0 270 0C446 98 370 0 370 0c-9 10-81 104-136 248z" />
          </svg>
      </div>
    <% else %>
      <% if @wrong_attempts != 2 %>
      <div class="scene">
        <div class = 'explosion-and-rocket'>
          <div id="axis" class="five">
            <%= image_tag 'astroid.png', class: "astroid object plane move-ne"%>
          </div>
            <%# <img class="astroid object plane move-ne" src="astroid.png" alt="star"> %>
          <%= image_tag 'explosion.png', class: "mini-explosion"%>
          <div class="rocket-container">
            <svg xmlns="http://www.w3.org/2000/svg" version="1" viewbox="0 0 741 1255" width="67.7" height="67.7" id="player1"
              class="rocket-1">
              <path fill="#1560d6"
                d="M565 728c-6 68-15 130-29 186 88 38 156 106 187 188 12-32 18-65 18-100 0-116-70-217-176-274zM265 1020l8 25h194l9-25H265z" />
              <path fill="#e83d37" d="M210 937c8 30 17 58 26 83h269c9-25 18-53 26-83H210z" />
              <path fill="#1560d6"
                d="M0 1002c0 35 6 68 18 100 31-82 99-150 187-188-14-55-23-118-29-186A314 314 0 0 0 0 1002z" />
              <path fill="#DFE3E5"
                d="M571 585c0-125-30-241-67-337a395 395 0 0 1-270 0c-36 94-64 209-64 337a1658 1658 0 0 0 34 329l6 23h321l5-23a1313 1313 0 0 0 35-329z" />
              <circle fill="#B8BDBF" cx="370" cy="481" r="100" />
              <path fill="#ead3b0" d="M455 481a85 85 0 1 1-170 0 85 85 0 0 1 170 0z" />
              <path fill="#1560d6" d="M234 248a394 394 0 0 0 270 0C446 98 370 0 370 0c-9 10-81 104-136 248z" />
            </svg>
          </div>
        </div>
        <%= image_tag 'sparkle.png', style: "width: 20px;", class: "star first"%>
        <%= image_tag 'sparkle.png', style: "width: 20px;", class: "star second"%>
        <%= image_tag 'sparkle.png', style: "width: 20px;", class: "star third"%>
        <%= image_tag 'sparkle.png', style: "width: 20px;", class: "star fourth"%>
        <%= image_tag 'sparkle.png', style: "width: 20px;", class: "star fifth"%>
      </div>
    <% else %>
    <div class="scene">
      <%= image_tag 'sparkle.png', style: "width: 20px;", class: "star first-slow"%>
      <%= image_tag 'sparkle.png', style: "width: 20px;", class: "star second-slow"%>
      <%= image_tag 'sparkle.png', style: "width: 20px;", class: "star third-slow"%>
      <%= image_tag 'sparkle.png', style: "width: 20px;", class: "star fourth-slow"%>
      <%= image_tag 'sparkle.png', style: "width: 20px;", class: "star fifth-slow"%>

      <%= image_tag 'astronaut.png', class: "astronaut-still"%>
      </div>
    <% end %>
    <% end %>
  <% end %>
  <br>
  <div class="container">

    <% if params[:display] != 'result' %>
    <h6 class = "sub-headings">Question <%= @question_number %></h6>
    <h4><%= @flashcard.question %></h4>
    <p class = "sub-headings"><%= @type.instruction %></p>
    <%= hidden_field_tag "question_type", @flashcard.question_type.name, { id: "question-type" } %>

      <% if @type.name == 'multiple-choice' %>
        <%= simple_form_for [@deck, @flashcard], url: deck_flashcard_attempts_path(@deck, @flashcard), method: :post do |f| %>
          <%# <%= f.input :answer, as: :buttons, collection: @options, checked: @options.first %>
          <%= f.input :answer, as: :radio_buttons, collection: @options, checked: @options.first, class: "multichoice-colour" %>
          <%= f.submit "Submit Answer", class: "btn pill" %>
        <% end %>
      <% end %>

      <% if @type.name == 'sort' %>
        <%= simple_form_for [@deck, @flashcard], html: {id: 'sort-form'}, url: deck_flashcard_attempts_path(@deck, @flashcard), method: :post do |f| %>
          <div id="sort-options" class="list-group col">
            <% @options.each do |option| %>
              <div class="list-group-item"><%= option %></div>
            <% end %>
          </div>
          <br>
          <input type="hidden" id="current_order"  name="current_order" value="" />
          <%= f.submit "Submit Answer", class: "btn pill" %>
        <% end %>
      <% end %>
    <% end %>
  </div>
    <div class = "results-info">
    <% if params[:display] == 'result' %>
      <% if @flashcard.attempt.attempt_correct %>
        <p class = "sub-headings green-h">Woohoo!</p>
        <h3 class = "full-headings">You were correct</h3>
      <% else %>
        <% if @wrong_attempts < 2 %>
          <p class = "sub-headings red-h">🚨 Critical Spaceship Damage</p>
          <p class = "sub-headings">You won't survive another hit!</p>
        <% else %>
          <p class = "sub-headings">Houston, we have a problem...</p>
        <% end %>
        <h3 class = "full-headings">You were incorrect</h3>
      <% end %>

      <% if @type.name == 'multiple-choice' %>
        <p class = "sub-headings">Flashcard <%= @question_number %></p>

        <p><%= @flashcard.question %></p>

        <p class = "correct-sub"><%= @flashcard.answer %></p>
        <% if !@flashcard.attempt.attempt_correct %>
          <p class = "incorrect-sub"><%= @submission %></p>
        <% end %>
      <% end %>
      <% if @type.name == 'sort' %>
        <p><%= @flashcard.question %></p>
        <% if !@flashcard.attempt.attempt_correct %>
          <h3>Your Submission</h3>
          <div class="list-group col">
            <% @submission_array.each do |submission_line| %>
              <div class="list-group-item"><%= submission_line %></div>
            <% end %>
          </div>
          <br>
        <% end %>
        <h3>Correct Answer</h3>
        <div class="list-group col">
          <% @answer_array.each do |answer_line| %>
            <div class="list-group-item"><%= answer_line %></div>
          <% end %>
        </div>
      <% end %>

      <br>
      <% if @wrong_attempts >= 2 %>
        <p class= "sub-headings">Better Luck Next Time</p>
        <%= link_to 'Restart Deck', deck_flashcard_path(@deck, @deck.flashcards.first), class: "btn pill text-white sticky" %>
      <% else %>
        <% if @next_question_index < @deck_card_count %>
          <%= link_to 'Next Question', deck_flashcard_path(@deck, @deck.flashcards[@next_question_index]), class: "btn pill text-white sticky"%>
        <% else %>
        <%# content_for(:body_attributes) do %>
          <%# data-turbolinks="false" %>
        <%# end %>
          <%= link_to 'Results', deck_path(@deck), class: "btn pill text-white sticky", data: {turbolinks: false} %>
        <% end %>
      <% end %>
    <% end %>
    </div>

</div>


<%# <script>
  console.log("working")
  section = document.querySelector('top')
  setTimeout(function() {
  //your code to be executed after 1 second
    section.style.visibility='hidden'
  }, 7000);
</script> %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Fly Flashcards - A not boring learning app</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= favicon_link_tag 'favicon.png'%>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>

    <title><%= meta_title %></title>
    <meta name="description" content="<%= meta_description %>">

    <!-- Facebook Open Graph data -->
    <meta property="og:title" content="<%= meta_title %>" />
    <meta property="og:type" content="website" />
    <meta property="og:url" content="<%= request.original_url %>" />
    <meta property="og:image" content="<%= meta_image %>" />
    <meta property="og:description" content="<%= meta_description %>" />
    <meta property="og:site_name" content="<%= meta_title %>" />

  </head>

  <body>

    <%# <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<% if @completed %>
  <div class = "home2">
<% else %>
  <div class = "home1">
<% end %>

<%# <h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p> %>
</div>
<div class="home-btn-container">
  <%= link_to "Start", topics_path, class: "btn home-btn" %>
</div>
<%# <button class = "btn purple"> Start </button> %>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to "#", class: "navbar-brand" do %>
    <%= image_tag "https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/logo.png" %>
    <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item active">
          <%= link_to "Home", "#", class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Messages", "#", class: "nav-link" %>
        </li>
        <li class="nav-item dropdown">
          <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Action", "#", class: "dropdown-item" %>
            <%= link_to "Another action", "#", class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>